"""상태 정의 — 6축 + 최종 상태."""
MACRO = ["CLEAR", "ARMED", "FIRED", "UNKNOWN"]
STRUCTURAL = ["STRUCTURAL_BULL", "BULL_WITH_LATE_CYCLE_RISK", "NEUTRAL", "STRUCTURAL_BEAR", "UNKNOWN"]
EARNINGS = ["BROAD_UPGRADES", "NARROW_UPGRADES", "FLAT", "MULTIPLE_ONLY_RALLY", "BROAD_DOWNGRADES", "UNKNOWN"]
VALUATION = ["CHEAP", "FAIR", "EXPENSIVE_SUPPORTED", "EXPENSIVE_FRAGILE", "UNKNOWN"]
TECHNICAL = ["TREND_STRONG", "EXTENDED", "PULLBACK", "TREND_WARNING", "TREND_BREAK", "RECOVERY", "UNKNOWN"]
SEMI = ["EARLY_RECOVERY", "EXPANSION", "SUPER_CYCLE", "OVER_ORDERING", "LATE_CYCLE",
        "MARGIN_PEAK", "CONTRACTION", "UNKNOWN"]
FINAL = ["RISK_ON", "RISK_ON_EXTENDED", "HOLD_WITH_HEDGE", "REDUCE_LEVERAGE",
         "DEFENSIVE", "EXITING", "UNKNOWN"]
